"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    '../img/blueheart.png',
    '../img/check.png',
    '../img/home.png',
    '../img/homebg.jpg',
    '../img/homebg2.jpg',
    '../img/homebg3.jpg',
    '../img/laporan.png',
    '../img/leftarrow4.png',
    '../img/leftarrow5.png',
    '../img/obat.png',
    '../img/obat1.jpg',
    '../img/obat2.webp',
    '../img/obat3.webp',
    '../img/obat4.webp',
    '../img/obat5.webp',
    '../img/obat6.webp',
    '../img/obat7.webp',
    '../img/obat8.webp',
    '../img/obat9.webp',
    '../img/obat10.webp',
    '../img/profile.png',
    '../img/redheart.png',
    '../img/rightarrow.png',
    '../img/samplebg.jpg',
    '../img/samplebg2.jpg',
    '../img/samplebg3.jpg',
    '../img/samplebg4.jpg',
    '../img/shop.png',
    '../img/trolly.png',
    '../img/trolly2.png',
    '../img/yellowheart.png',
    'adila/payment.kv',
    'adila/paySuccess.kv',
    'aisha/pembelianapoteker/pembelianapoteker.kv',
    'detha/pembelian/pembelian.kv',
    'shifa/homeapoteker/homeapoteker.kv',
    'shifa/homedokter/homedokter.kv',
    'shifa/homeuser/homeuser.kv',
    'shifa/signin/signin.kv',
    'shifa/signindokter/signindokter.kv',
    'shifa/signinapoteker/signinapoteker.kv',
    'shifa/signup/signup.kv',
    'shifa/signupdokter/signupdokter.kv',
    'shifa/signupapoteker/signupapoteker.kv',
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
